name: CI

on:
  pull_request:
    types:
      - ready_for_review
      - reopened
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

  # manual trigger from Github UI - Action tab
  workflow_dispatch:

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Run eslint
        run: yarn lint
